---

- name: Check Elasticsearch version
  assert:
    that:
      - es_version != ""
      - es_version > 0
    msg: "Elasticsearch version must be numeric, {{ es_version }} was given"
  tags: [ "check_vars" ]

- name: get the index list
  uri: 
    url: "{{ cluster_addr }}/_cat/indices"
    method: GET
  delegate_to: localhost
  register: indices
  
- name: sort the indexes by deleted
  shell: echo "{{ indices }}" | sort -rnk7 | awk '{print $3}'
  register: to_process
  
- name: Optimize a cluster
  uri: 
    url: "{{ cluster_addr }}/{{ item }}/{{ optimize_endpoint }}?max_num_segments={{ segments }}"
    method: GET
  delegate_to: localhost
  with_items: "{{ to_process }}"
