---

- name: Check Elasticsearch version
  assert:
    that:
      - es_version != ""
      - es_version > 0
    msg: "Elasticsearch version must be numeric, {{ es_version }} was given"
  tags: [ "check_vars" ]

- name: Check index name is present
  assert:
    that:
      - index != ""
    msg: "Index name is missing"
  tags: [ "check_vars" ]

- name: Optimize an index
  uri: 
    url: "{{ endpoint }}"
    method: GET
  delegate_to: localhost
