---

- name: Check for the number of replicas
  assert:
    that:
      - replicas != ""
      - replicas >= 0
    msg: "Replicas must be >= 0, {{ replicas }} given"
  tags: [ "check_vars" ]

- name: Update number of replicas
  uri: 
    url: "{{ endpoint }}"
    method: PUT
    body: "{{ query }}"
    body_format: json
  delegate_to: localhost
