---

- name: Check that refresh time is present
  assert:
    that:
      - refresh_time != ""
    msg: "Refresh time is missing"
  tags: [ "check_vars" ]

- name: Update refresh time replicas
  uri: 
    url: "{{ endpoint }}"
    method: PUT
    body: "{{ query }}"
    body_format: json
  delegate_to: localhost
